# Generated by Django 4.1.5 on 2023-01-20 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0002_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
